version: '1.x'
services:
 php-btech:
    build: .
    ports:
      - "8083:8080"
    volumes:
      - ./:/var/www/html
  mysql-btech:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=s